name: 'Bonusly for GitHub'
description: 'A GitHub Action for Bonusly'
author: 'Jody Heavener'
inputs:
  api-token:
    required: true
    description: 'Your Bonusly API Access Token'
runs:
  using: 'node12'
  main: 'dist/index.js'
