name: 'Bonusly for GitHub'
description: 'A GitHub Action for Bonusly'
author: 'Jody Heavener'
inputs:
  bonusly-token:
    required: true
    description: 'A Bonusly API Access Token'
  github-token:
    required: true
    description: 'A GitHub Personal Access Token'
runs:
  using: 'node12'
  main: 'dist/index.js'
