name: 'bonusly'

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run build-test
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./
        with:
          api-token: ${{ secrets.BONUSLY_API_TOKEN }}
