name: Bonusly

on:
  pull_request:
    types: [closed]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          yarn install
      - run: |
          yarn build-test
  merge-allocate:
    runs-on: ubuntu-latest
    name: Bonusly
    steps:
      - uses: actions/checkout@v2
      - name: Merge allocate
        uses: ./
        with:
          api-token: ${{ secrets.BONUSLY_API_TOKEN }}
